services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - data:/data/db
  backend:
    image: python:3.11-alpine
    ports:
      - "7050"
    depends_on:
      - db
  gui:
    build:
      context: ./metis-gui
      dockerfile: ../gui.dockerfile
    ports:
      - 5000:5000
    depends_on:
      - bff
  bff:
    build:
      context: ./metis-bff
      dockerfile: ../bff.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db

volumes:
  data: