services:
  db:
    image: postgres:14.6
    volumes:
      - data:/data/db
  backend:
    image: python:3.11
    working_dir: ./metis-backend
    ports:
      - "7050"
    depends_on:
      - db
  gui:
    image: node:18
    working_dir: ./metis-gui
    ports:
      - "5000"
    depends_on:
      - bff
  bff:
    image: node:18
    working_dir: ./metis-bff
    ports:
      - "3000"
    depends_on:
      - backend

volumes:
  data: