services:
  db:
    image: postgres:14.6
    volumes:
      - data:/data/db
  backend:
    image: python:3.11
    ports:
      - "7050"
    depends_on:
      - db
  gui:
    build: ./gui.dockerfile
    ports:
      - "5000"
    depends_on:
      - bff
  bff:
    image: node:18
    build: ./bff.dockerfile
    ports:
      - "3000"
    depends_on:
      - backend
      - db

volumes:
  data: